version: "3"

services:
  # redis:
  #   image: redis:alpine
  #   command: ['redis-server', '--bind', '0.0.0.0', '--port', '6379']
  #   ports:
  #     - '6379:6379'

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/vendor/bundle:/usr/local/bundle
      - /etc/ssl:/etc/ssl
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development
      CORS_ORIGINS: "localhost:3000,127.0.0.1:3000"
      # REDIS_URL: redis://redis:6379
